### ISSUE TITLE
Code is incomplete

### ISSUE THREAD

**Issue by feidieufo** [tinnerhrhe/MTDiff#1]
I cannot find models.TasksAttTemporalUnet.
I cannot download the dataset.

**Comment by tinnerhrhe** [comment]
Sorry for this late reply. I've been really busy lately.
models.TasksAttTemporalUnet is unuseful for this project. You are expected to follow the instructions to run MTDiff.
Dataset can be downloaded via google drive,  and I have also uploaded the prompt dataset used in the paper for reproduction.
