### ISSUE TITLE
Could you please upload the requirements.txt file?

### ISSUE THREAD

**Issue by nuomizai** [tinnerhrhe/MTDiff#2]
Thanks for your code! However, I found it hard to config the right conda environment. So could you please upload the requirements.txt file or write some guidance command to create the environment?

**Comment by chenyinlin1** [comment]
Hi, did you successfully build the environment for this project?

**Comment by nuomizai** [comment]
> Hi, did you successfully build the environment for this project?

Yes, this project is based on [diffuser](https://github.com/jannerm/diffuser). So you can just build the environments with the environment.yml in that project. However, I remember that this project was incomplete, so I didn't follow this project.

**Comment by tinnerhrhe** [comment]
Sorry for this late reply. I've been really busy lately.
I have updated this repo and added the installation section in the README. You can install the packages in the environment.yml to launch the experiments.
